#############################################################################
# Makefile for building: build/nvImageBrowser
# Generated by qmake (2.01a) (Qt 4.7.2) on: Fri Oct 21 15:41:34 2011
# Project:  nvImageBrowser.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile nvImageBrowser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-32 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iobjects
LINK          = g++
LFLAGS        = -m32 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = objects/

####### Files

SOURCES       = sources/main.cpp \
		sources/appcontroler.cpp \
		sources/appsettings.cpp objects/moc_appcontroler.cpp \
		objects/moc_appsettings.cpp \
		objects/qrc_resources.cpp
OBJECTS       = objects/main.o \
		objects/appcontroler.o \
		objects/appsettings.o \
		objects/moc_appcontroler.o \
		objects/moc_appsettings.o \
		objects/qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		nvImageBrowser.pro
QMAKE_TARGET  = nvImageBrowser
DESTDIR       = build/
TARGET        = build/nvImageBrowser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nvImageBrowser.pro  /usr/share/qt4/mkspecs/linux-g++-32/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile nvImageBrowser.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile nvImageBrowser.pro

dist: 
	@$(CHK_DIR_EXISTS) objects/nvImageBrowser1.0.0 || $(MKDIR) objects/nvImageBrowser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) objects/nvImageBrowser1.0.0/ && $(COPY_FILE) --parents sources/appcontroler.h sources/appsettings.h objects/nvImageBrowser1.0.0/ && $(COPY_FILE) --parents resources.qrc objects/nvImageBrowser1.0.0/ && $(COPY_FILE) --parents sources/main.cpp sources/appcontroler.cpp sources/appsettings.cpp objects/nvImageBrowser1.0.0/ && (cd `dirname objects/nvImageBrowser1.0.0` && $(TAR) nvImageBrowser1.0.0.tar nvImageBrowser1.0.0 && $(COMPRESS) nvImageBrowser1.0.0.tar) && $(MOVE) `dirname objects/nvImageBrowser1.0.0`/nvImageBrowser1.0.0.tar.gz . && $(DEL_FILE) -r objects/nvImageBrowser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: objects/moc_appcontroler.cpp objects/moc_appsettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) objects/moc_appcontroler.cpp objects/moc_appsettings.cpp
objects/moc_appcontroler.cpp: sources/appcontroler.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sources/appcontroler.h -o objects/moc_appcontroler.cpp

objects/moc_appsettings.cpp: sources/appsettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sources/appsettings.h -o objects/moc_appsettings.cpp

compiler_rcc_make_all: objects/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) objects/qrc_resources.cpp
objects/qrc_resources.cpp: resources.qrc
	/usr/bin/rcc -name resources resources.qrc -o objects/qrc_resources.cpp

compiler_image_collection_make_all: objects/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) objects/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

objects/main.o: sources/main.cpp sources/appcontroler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/main.o sources/main.cpp

objects/appcontroler.o: sources/appcontroler.cpp sources/appcontroler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/appcontroler.o sources/appcontroler.cpp

objects/appsettings.o: sources/appsettings.cpp sources/appsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/appsettings.o sources/appsettings.cpp

objects/moc_appcontroler.o: objects/moc_appcontroler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_appcontroler.o objects/moc_appcontroler.cpp

objects/moc_appsettings.o: objects/moc_appsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_appsettings.o objects/moc_appsettings.cpp

objects/qrc_resources.o: objects/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/qrc_resources.o objects/qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

